export type MenuItem = {
    id: string;
    name: string;
    description: string;
    price: string;
    category: string;
    image: string;
    veg: boolean;
    spicy?: boolean;
    bestseller?: boolean;
};

export const MENU_CATEGORIES = ["Starters", "Seafood", "Mains", "Biryani", "Desserts", "Beverages"];

export const MENU_ITEMS: MenuItem[] = [
    // === STARTERS (10 items) ===
    {
        id: 's1',
        name: "Vizag 'Beach Rd' Chilli Prawns",
        description: "Crispy fried fresh prawns tossed in a fiery green chilli and curry leaf masala.",
        price: "₹450",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
        bestseller: true,
    },
    {
        id: 's2',
        name: "Guntur Karam Kodi Vepudu",
        description: "Boneless chicken cubes wok-tossed with Guntur red chillies and cashew powder.",
        price: "₹380",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 's3',
        name: "Crispy Corn Kernels",
        description: "Sweet corn fried golden brown and dusted with pepper and sea salt.",
        price: "₹290",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1551462147-37885acc36f1?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 's4',
        name: "Paneer Tikka",
        description: "Marinated cottage cheese cubes grilled in tandoor with bell peppers and onions.",
        price: "₹320",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=800",
        veg: true,
        bestseller: true,
    },
    {
        id: 's5',
        name: "Vegetable Samosa",
        description: "Crispy golden pastry filled with spiced potatoes and green peas.",
        price: "₹180",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 's6',
        name: "Gobi Manchurian",
        description: "Crispy cauliflower florets tossed in a sweet and spicy Indo-Chinese sauce.",
        price: "₹280",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&q=80&w=800",
        veg: true,
        spicy: true,
    },
    {
        id: 's7',
        name: "Chicken Lollipop",
        description: "Spicy chicken drumettes marinated in ginger-garlic and deep fried crispy.",
        price: "₹350",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
        bestseller: true,
    },
    {
        id: 's8',
        name: "Aloo Tikki Chaat",
        description: "Crispy potato patties topped with chutneys, yogurt, and crunchy sev.",
        price: "₹220",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 's9',
        name: "Fish Amritsari",
        description: "Batter-fried fish fillets with carom seeds and spicy chaat masala.",
        price: "₹420",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1544943910-4c1dc44aab44?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 's10',
        name: "Hara Bhara Kebab",
        description: "Spinach and green pea patties with mint and coriander, pan-fried golden.",
        price: "₹260",
        category: "Starters",
        image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },

    // === SEAFOOD (10 items) ===
    {
        id: 'f1',
        name: "Signature Clay Pot Fish Curry",
        description: "Seer fish simmered in a tangy tamarind and tomato gravy, served in a clay pot.",
        price: "₹550",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
        bestseller: true,
    },
    {
        id: 'f2',
        name: "Butter Garlic Prawns",
        description: "Jumbo prawns sautéed in rich butter, garlic, and fresh parsley sauce.",
        price: "₹520",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&q=80&w=800",
        veg: false,
    },
    {
        id: 'f3',
        name: "Crab Masala",
        description: "Fresh crab cooked in aromatic spices with onion, tomato, and coconut gravy.",
        price: "₹620",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
        bestseller: true,
    },
    {
        id: 'f4',
        name: "Tandoori Fish Tikka",
        description: "Boneless fish marinated in yogurt and spices, chargrilled to perfection.",
        price: "₹480",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&q=80&w=800",
        veg: false,
    },
    {
        id: 'f5',
        name: "Squid Pepper Fry",
        description: "Tender squid rings stir-fried with crushed pepper, curry leaves, and onions.",
        price: "₹490",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 'f6',
        name: "Goan Fish Curry",
        description: "Pomfret in spicy coconut and kokum gravy, served Goan style.",
        price: "₹580",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 'f7',
        name: "Lobster Thermidor",
        description: "Whole lobster baked with creamy cheese sauce and fresh herbs.",
        price: "₹1200",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&q=80&w=800",
        veg: false,
        bestseller: true,
    },
    {
        id: 'f8',
        name: "Prawn Koliwada",
        description: "Mumbai-style spiced and batter-fried prawns with tangy dip.",
        price: "₹480",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 'f9',
        name: "Fish Moilee",
        description: "Kerala-style fish cooked in mild coconut milk with green chilies.",
        price: "₹520",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800",
        veg: false,
    },
    {
        id: 'f10',
        name: "Chilli Garlic Crab",
        description: "Whole crab wok-tossed in fiery chilli garlic sauce, served with buns.",
        price: "₹750",
        category: "Seafood",
        image: "https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },

    // === MAINS (10 items) ===
    {
        id: 'm1',
        name: "AzureFork Special Thali",
        description: "A grand feast with 2 veg curries, dal, sambar, rasam, flavored rice, roti, and sweet.",
        price: "₹350",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800",
        veg: true,
        bestseller: true,
    },
    {
        id: 'm2',
        name: "Andhra Chicken Curry",
        description: "Homestyle chicken curry cooked with poppy seeds and coconut paste.",
        price: "₹420",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 'm3',
        name: "Mutton Rogan Josh",
        description: "Tender mutton slow-cooked in aromatic Kashmiri spices and yogurt gravy.",
        price: "₹520",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
        bestseller: true,
    },
    {
        id: 'm4',
        name: "Paneer Butter Masala",
        description: "Soft paneer cubes in a rich, creamy tomato and cashew gravy.",
        price: "₹340",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800",
        veg: true,
        bestseller: true,
    },
    {
        id: 'm5',
        name: "Dal Tadka",
        description: "Yellow lentils tempered with cumin, garlic, and dried red chillies.",
        price: "₹220",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'm6',
        name: "Butter Chicken",
        description: "Tender chicken tikka in creamy tomato-butter sauce, a North Indian classic.",
        price: "₹400",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=800",
        veg: false,
        bestseller: true,
    },
    {
        id: 'm7',
        name: "Lamb Nihari",
        description: "Slow-cooked lamb shanks in rich, spiced gravy with bone marrow.",
        price: "₹580",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1545247181-516773cae754?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 'm8',
        name: "Palak Paneer",
        description: "Fresh cottage cheese cubes in creamy spinach gravy with garlic.",
        price: "₹320",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'm9',
        name: "Chicken Chettinad",
        description: "Fiery South Indian chicken curry with freshly ground spices.",
        price: "₹440",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 'm10',
        name: "Malai Kofta",
        description: "Fried paneer-potato dumplings in rich cashew and cream gravy.",
        price: "₹360",
        category: "Mains",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },

    // === BIRYANI (8 items) ===
    {
        id: 'b1',
        name: "Ulavacharu Chicken Biryani",
        description: "Long grain aromatic basmati rice cooked with horse gram sauce and tender chicken.",
        price: "₹480",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
        bestseller: true,
    },
    {
        id: 'b2',
        name: "Prawns Fry Piece Biryani",
        description: "Flavorful biryani rice served with a generous portion of spicy prawn fry.",
        price: "₹520",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
    },
    {
        id: 'b3',
        name: "Vegetable Dum Biryani",
        description: "Fragrant basmati rice layered with mixed vegetables and aromatic spices.",
        price: "₹320",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'b4',
        name: "Mutton Dum Biryani",
        description: "Slow-cooked dum biryani with succulent mutton pieces and saffron-infused rice.",
        price: "₹550",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
        bestseller: true,
    },
    {
        id: 'b5',
        name: "Hyderabadi Chicken Biryani",
        description: "Authentic Hyderabadi style dum biryani with tender chicken and fragrant rice.",
        price: "₹450",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=800",
        veg: false,
        spicy: true,
        bestseller: true,
    },
    {
        id: 'b6',
        name: "Fish Biryani",
        description: "Aromatic rice layered with spiced fish fillets and caramelized onions.",
        price: "₹480",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=800",
        veg: false,
    },
    {
        id: 'b7',
        name: "Egg Biryani",
        description: "Flavorful biryani with boiled eggs and aromatic masala rice.",
        price: "₹320",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&q=80&w=800",
        veg: false,
    },
    {
        id: 'b8',
        name: "Paneer Biryani",
        description: "Cottage cheese cubes layered with fragrant saffron rice and mint.",
        price: "₹380",
        category: "Biryani",
        image: "https://images.unsplash.com/photo-1642821373181-696a54913e93?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },

    // === DESSERTS (10 items) ===
    {
        id: 'd1',
        name: "Junnu (Kharvas)",
        description: "Traditional milk pudding made with colostrum milk and jaggery.",
        price: "₹150",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'd2',
        name: "Gulab Jamun",
        description: "Soft milk dumplings soaked in warm rose and cardamom flavored sugar syrup.",
        price: "₹120",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1666190077281-4fa31ec6de56?auto=format&fit=crop&q=80&w=800",
        veg: true,
        bestseller: true,
    },
    {
        id: 'd3',
        name: "Rasmalai",
        description: "Soft paneer discs immersed in chilled saffron and cardamom milk.",
        price: "₹160",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'd4',
        name: "Payasam",
        description: "Traditional South Indian rice pudding cooked with milk, jaggery, and cashews.",
        price: "₹140",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1571864358893-6d50f20e8425?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'd5',
        name: "Kulfi Falooda",
        description: "Traditional Indian ice cream with rose syrup, vermicelli, and basil seeds.",
        price: "₹180",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800",
        veg: true,
        bestseller: true,
    },
    {
        id: 'd6',
        name: "Jalebi with Rabri",
        description: "Crispy sweet spirals served with thick, creamy reduced milk.",
        price: "₹150",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1666190077281-4fa31ec6de56?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'd7',
        name: "Gajar Ka Halwa",
        description: "Slow-cooked grated carrots in milk with ghee, nuts, and cardamom.",
        price: "₹160",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'd8',
        name: "Double Ka Meetha",
        description: "Hyderabadi bread pudding soaked in saffron milk and topped with dry fruits.",
        price: "₹170",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1571864358893-6d50f20e8425?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'd9',
        name: "Phirni",
        description: "Creamy ground rice pudding flavored with cardamom and rose water.",
        price: "₹130",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'd10',
        name: "Mysore Pak",
        description: "Rich, melt-in-mouth sweet made with gram flour, ghee, and sugar.",
        price: "₹140",
        category: "Desserts",
        image: "https://images.unsplash.com/photo-1666190077281-4fa31ec6de56?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },

    // === BEVERAGES (10 items) ===
    {
        id: 'bev1',
        name: "Rose Milk",
        description: "Chilled milk with homemade rose syrup and sabja seeds.",
        price: "₹120",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'bev2',
        name: "Masala Chai",
        description: "Authentic Indian spiced tea brewed with ginger, cardamom, and cinnamon.",
        price: "₹80",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&q=80&w=800",
        veg: true,
        bestseller: true,
    },
    {
        id: 'bev3',
        name: "Fresh Lime Soda",
        description: "Refreshing lime juice with soda, available sweet or salted.",
        price: "₹90",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'bev4',
        name: "Mango Lassi",
        description: "Creamy yogurt smoothie blended with sweet Alphonso mango pulp.",
        price: "₹150",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&q=80&w=800",
        veg: true,
        bestseller: true,
    },
    {
        id: 'bev5',
        name: "Filter Coffee",
        description: "Traditional South Indian coffee brewed with chicory and fresh milk.",
        price: "₹100",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&q=80&w=800",
        veg: true,
        bestseller: true,
    },
    {
        id: 'bev6',
        name: "Buttermilk (Chaas)",
        description: "Spiced yogurt drink with cumin, curry leaves, and fresh coriander.",
        price: "₹80",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'bev7',
        name: "Tender Coconut Water",
        description: "Fresh tender coconut water served chilled with coconut malai.",
        price: "₹120",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'bev8',
        name: "Badam Milk",
        description: "Warm almond-infused milk with saffron and cardamom.",
        price: "₹140",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'bev9',
        name: "Jigarthanda",
        description: "Madurai special cold drink with almond gum, sarsaparilla, and ice cream.",
        price: "₹160",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
    {
        id: 'bev10',
        name: "Thandai",
        description: "Festive drink with milk, almonds, fennel seeds, and rose petals.",
        price: "₹150",
        category: "Beverages",
        image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&q=80&w=800",
        veg: true,
    },
];

export const CHEF_SPECIALS = [
    {
        id: 'cs1',
        title: "Whole Grilled Pomfret",
        subtitle: "Tandoori Marinade",
        image: "https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=800",
        description: "Fresh catch of the day, marinated in our secret tandoori spice blend and grilled to perfection over charcoal.",
    },
    {
        id: 'cs2',
        title: "Bamboo Chicken",
        subtitle: "Araku Style",
        image: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&q=80&w=800",
        description: "Chicken marinated in local herbs, stuffed inside bamboo shoots and slow-cooked over open fire without oil.",
    },
    {
        id: 'cs3',
        title: "Lobster Thermidor",
        subtitle: "Coastal Fusion",
        image: "https://images.unsplash.com/photo-1559742811-822873691df8?auto=format&fit=crop&q=80&w=800",
        description: "Fresh lobster meat cooked in a rich creamy sauce with egg yolks and brandy, topped with oven-browned cheese.",
    },
];

export const REVIEWS = [
    {
        id: 'r1',
        name: "Arjun Reddy",
        city: "Visakhapatnam",
        rating: 5,
        text: "The best seafood place in Vizag! The Crab Fry was absolutely authentic and the service was top notch. Highly recommended for family dinners.",
        source: "Google",
    },
    {
        id: 'r2',
        name: "Sneha Gupta",
        city: "Hyderabad",
        rating: 5,
        text: "Visited during my vacation. The ambiance is stunning, especially the ocean theme. The Prawn Biryani is a must-try!",
        source: "Zomato",
    },
    {
        id: 'r3',
        name: "Michael Chen",
        city: "Tourist",
        rating: 4,
        text: "Fresh catch indeed. The grilled fish was juicy and flavorful. A bit spicy for my taste but manageable. Great view!",
        source: "Google",
    },
];
